services:
  flask-app:
    build: .
    image: yw5490/flask-todo-app:latest
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: