route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - api_url: 'https://hooks.slack.com/services/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'
        channel: '#assignment-2'
        send_resolved: true
        text: "{{ range .Alerts }}{{ .Annotations.summary }} - {{ .Annotations.description }}\n{{ end }}"

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']